import { Inter } from 'next/font/google'
import './globals.css'
import HeadBar from '@/components/Header/HeadBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SolGuard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full relative'>
          <HeadBar/>
          {children}
        </div>
      </body>
    </html>
  )
}
