import "@rainbow-me/rainbowkit/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import HeadBar from "@/components/Header/HeadBar";
import Provider from "./provider";
import dynamic from "next/dynamic";
import "react-toastify/dist/ReactToastify.css";
import "./loaderStyle.css";

const inter = Inter({ subsets: ["latin"] });

const NoSSR = dynamic(() => import("./provider"), { ssr: false });

export const metadata = {
  title: "SolGuard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full relative">
          <NoSSR>
            <>
              <HeadBar />
              {children}
            </>
          </NoSSR>
        </div>
      </body>
    </html>
  );
}
